export default function PrivacyPolicy() {
    return (
      <div className="max-w-4xl mx-auto px-4 py-8 font-sans text-gray-800">
        <h1 className="text-red-500 text-2xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-sm mb-4">Last updated: July 07, 2023</p>
        
        <p className="text-sm mb-4">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        
        <p className="text-sm mb-6">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
        </p>
  
        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">Interpretation and Definitions</h2>
          <h3 className="text-lg font-medium mb-2">Interpretation</h3>
          <p className="text-sm mb-4">
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          
          <h3 className="text-lg font-medium mb-2">Definitions</h3>
          <ul className="list-disc pl-6 text-sm space-y-2 mb-4">
            <li><span className="font-medium">Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><span className="font-medium">Affiliate</span> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><span className="font-medium">Application</span> refers to Scope India, the software program provided by the Company.</li>
            <li><span className="font-medium">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to SCOPE INDIA SECURITY SOLUTIONS PVT. LTD., 46, Sector 11, Noida, Uttar Pradesh 201301.</li>
            <li><span className="font-medium">Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><span className="font-medium">Country</span> refers to: Uttar Pradesh, India</li>
            <li><span className="font-medium">Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><span className="font-medium">Personal Data</span> is any information that relates to an identified or identifiable individual.</li>
            <li><span className="font-medium">Service</span> refers to the Application.</li>
            <li><span className="font-medium">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><span className="font-medium">Third-party Social Media Service</span> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
            <li><span className="font-medium">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><span className="font-medium">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
        </section>
  
        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">Collecting and Using Your Personal Data</h2>
          <h3 className="text-lg font-medium mb-2">Types of Data Collected</h3>
          
          <h4 className="text-base font-medium mb-2">Personal Data</h4>
          <p className="text-sm mb-4">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc pl-6 text-sm space-y-2 mb-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>
  
          <h4 className="text-base font-medium mb-2">Usage Data</h4>
          <p className="text-sm mb-4">
            Usage Data is collected automatically when using the Service.
          </p>
          <p className="text-sm mb-4">
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p className="text-sm mb-4">
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>
          <p className="text-sm mb-4">
            We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
          </p>
        </section>
  
        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">Tracking Technologies and Cookies</h2>
          <p className="text-sm mb-4">
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
          </p>
          <ul className="list-disc pl-6 text-sm space-y-2 mb-4">
            <li><span className="font-medium">Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
            <li><span className="font-medium">Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
          </ul>
          <p className="text-sm mb-4">
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
          </p>
          <p className="text-sm mb-4">
            We use both Session and Persistent Cookies for the purposes set out below:
          </p>
          <ul className="list-disc pl-6 text-sm space-y-2 mb-4">
            <li>
              <span className="font-medium">Necessary / Essential Cookies</span>
              <br />
              Type: Session Cookies
              <br />
              Administered by: Us
              <br />
              Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
            </li>
            <li>
              <span className="font-medium">Cookies Policy / Notice Acceptance Cookies</span>
              <br />
              Type: Persistent Cookies
              <br />
              Administered by: Us
              <br />
              Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
            </li>
            <li>
              <span className="font-medium">Functionality Cookies</span>
              <br />
              Type: Persistent Cookies
              <br />
              Administered by: Us
              <br />
              Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
            </li>
          </ul>
        </section>
  
        {/* Additional sections would be added here to complete the privacy policy */}
  
        <footer className="mt-8 pt-4 border-t border-gray-200 text-sm text-gray-600">
          <h2 className="text-lg font-semibold mb-2">Contact Us</h2>
          <p className="mb-2">If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>By email: info@scopeindia.org</li>
            <li>By visiting this page on our website: https://www.scopeindia.org/contact</li>
            <li>By phone number: 9999999999</li>
            <li>By mail: 46, Sector 11, Noida, Uttar Pradesh 201301</li>
          </ul>
        </footer>
      </div>
    )
  }
  
  