export default function PrivacyPolicy() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8 font-sans text-gray-800">
      <h1 className="text-red-500 text-4xl font-bold mb-2 text-center">Privacy Policy</h1>
      <p className="text-sm mb-4">Last updated: November 22, 2024</p>

      <p className="text-sm mb-4">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>

      <p className="text-sm mb-6">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
      </p>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Interpretation and Definitions</h2>
        <h3 className="text-lg font-medium mb-2">Interpretation</h3>
        <p className="text-sm mb-4">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="text-lg font-medium mb-2">Definitions</h3>
        <ul className="list-disc pl-6 text-sm space-y-2 mb-4">
          <li><span className="font-medium">Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><span className="font-medium">Company</span> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Guru Kripa R.C. Security Services, Noida, GB Nagar, Uttar Pradesh, 201301.</li>
          <li><span className="font-medium">Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><span className="font-medium">Country</span> refers to: India</li>
          <li><span className="font-medium">Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li><span className="font-medium">Personal Data</span> is any information that relates to an identified or identifiable individual.</li>
          <li><span className="font-medium">Service</span> refers to the Website.</li>
          <li><span className="font-medium">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li><span className="font-medium">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><span className="font-medium"></span>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Collecting and Using Your Personal Data</h2>
        <h3 className="text-lg font-medium mb-2">Types of Data Collected</h3>

        <h4 className="text-base font-medium mb-2">Personal Data</h4>
        <p className="text-sm mb-4">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="list-disc pl-6 text-sm space-y-2 mb-4">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-base font-medium mb-2">Usage Data</h4>
        <p className="text-sm mb-4">
          Usage Data is collected automatically when using the Service.
        </p>
        <p className="text-sm mb-4">
          Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p className="text-sm mb-4">
          When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
        </p>
        <p className="text-sm mb-4">
          We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Tracking Technologies and Cookies</h2>
        <p className="text-sm mb-4">
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
        </p>
        <ul className="list-disc pl-6 text-sm space-y-2 mb-4">
          <li><span className="font-medium">Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
          <li><span className="font-medium">Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
        </ul>
        <p className="text-sm mb-4">
          Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
        </p>
        <p className="text-sm mb-4">
          We use both Session and Persistent Cookies for the purposes set out below:
        </p>
        <ul className="list-disc pl-6 text-sm space-y-2 mb-4">
          <li>
            <span className="font-medium">Necessary / Essential Cookies</span>
            <br />
            Type: Session Cookies
            <br />
            Administered by: Us
            <br />
            Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
          </li>
          <li>
            <span className="font-medium">Cookies Policy / Notice Acceptance Cookies</span>
            <br />
            Type: Persistent Cookies
            <br />
            Administered by: Us
            <br />
            Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
          </li>
          <li>
            <span className="font-medium">Functionality Cookies</span>
            <br />
            Type: Persistent Cookies
            <br />
            Administered by: Us
            <br />
            Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Use of Your Personal Data</h2>
        <ul className="list-disc pl-6 text-sm space-y-2 mb-4">
          <li>To provide and maintain our Service: Including to monitor the usage of our Service.
          </li>
          <li>
            To manage Your Account: To manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
          </li>
          <li>
            For the performance of a contract: The development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or of any other contract with Us through the Service.
          </li>
          <li>
            To contact You: By email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including security updates, when necessary or reasonable for their implementation.
          </li>
          <li>
            To provide You with updates: News, special offers, and general information about other goods, services, and events We offer that are similar to those You have already purchased or enquired about unless You have opted not to receive such information.
          </li>
          <li>
            To manage Your requests: To attend and manage Your requests to Us.
          </li>
          <li>
            For business transfers: To evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, where Personal Data held by Us about Service users is among the assets transferred.
          </li>
          <li>
            For other purposes: Such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Service, products, services, marketing, and user experience.
          </li>
          <li>
            With Service Providers: To monitor and analyze the use of our Service and to contact You.
          </li>
          <li>
            For business transfers: We may share or transfer Your personal information in connection with or during negotiations of any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
          </li>
          <li>
            With Affiliates: We may share Your information with Our affiliates, in which case We will require them to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners, or other companies that We control or that are under common control with Us.
          </li>
          <li>
            With business partners: To offer You certain products, services, or promotions.
          </li>
          <li>
            With other users: When You share personal information or interact in public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
          </li>
          <li>
            With Your consent: We may disclose Your personal information for any other purpose with Your consent.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Retention of Your Personal Data</h2>
        <p>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
        </p>
        <br />
        <p>
          The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Transfer of Your Personal Data</h2>
        <p>
          Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
        </p>
        <br />
        <p>
          Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
        </p>
        <br />
        <p>
          The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
        </p>
      </section>


      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Disclosure of Your Personal Data</h2>
        <h3 className="text-lg font-medium mb-2">Business Transactions</h3>
        <p>
          If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
        </p>
        <br />

        <h3 className="text-lg font-medium mb-2">Law enforcement</h3>
        <p>
          Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
        </p>
        <br />

        <h3 className="text-lg font-medium mb-2">Other legal requirements</h3>
        <p>
          The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
        </p>
        <br />
        <ul className="list-disc pl-6 text-sm space-y-2 mb-4">
          <li>
            Comply with a legal obligation
          </li>
          <li>
            Protect and defend the rights or property of the Company
          </li>
          <li>
            Prevent or investigate possible wrongdoing in connection with the Service
          </li>
          <li>
            Protect the personal safety of Users of the Service or the public
          </li>
          <li>
            Protect against legal liability
          </li>
        </ul>
        <br />

        <h3 className="text-lg font-medium mb-2">Security of Your Personal Data</h3>
        <p>
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </p>
        <br />

        <h3 className="text-lg font-medium mb-2">Children&apos;s Privacy</h3>
        <p>
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers. If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information.
        </p>
        <br />

        <h3 className="text-lg font-medium mb-2">Links to Other Websites</h3>
        <p>
          Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>
        <br />

        <h3 className="text-lg font-medium mb-2">Changes to this Privacy Policy</h3>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>
        <br />

      </section>


      {/* Additional sections would be added here to complete the privacy policy */}

      <footer className="mt-8 pt-4 border-t border-gray-200 text-sm text-gray-600">
        <h2 className="text-lg font-semibold mb-2">Contact Us</h2>
        <p className="mb-2">If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>By email: MaharanaPratap.gkrcss@gmail.com</li>
          {/* <li>By visiting this page on our website: https://www.scopeindia.org/contact</li> */}
          <li>By phone number: +917982606235</li>
        </ul>
      </footer>
    </div>
  )
}